import pandas as pd
import numpy as np
import torch
import math
from read_neighbor import read_neighbor_list
from generate_feature import generate_feature_mat
from generate_feature import generate_Q_feature
from symmetry_functionsV2 import *
import torch.utils.data as data


def generate_Q_and_its_neighbors_feature(step,Q):  #step,Q,F,Q_feature_list,F_feature_list
    Q_feature_list_one_configuration = []
    for i in range(0,lattice_num):
        Q_feature_list_one_configuration_one_lattice = []
        count_all = 0
        for j in range(0,len(num_of_nodes_neighbor_each_layer)):
            count =0
            num_of_points = num_of_nodes_neighbor_each_layer[j]
            Q_temp = []
            while (count < num_of_points):
                Q_temp.append(Q[0,neighbor_2d[i,count_all]].item())
                count = count+1
                count_all = count_all + 1
            Q_feature_list_one_configuration_one_lattice.append(Q_temp)
            
        Q_feature_list_one_configuration.append(Q_feature_list_one_configuration_one_lattice)
    return Q_feature_list_one_configuration  #the q value of the center point, the qs value of the 4 neighbors around it, the qs value of the 4 neighbors on the next layer...

def screenANDscale_tensor(IR_tensor):
    tensor_mean = torch.mean(IR_tensor).item()
    tensor_dev = torch.std(IR_tensor).item()
    IR_tensor[IR_tensor > (tensor_mean + 3*tensor_dev)] = tensor_mean + 3*tensor_dev
    IR_tensor[IR_tensor < (tensor_mean - 3*tensor_dev)] = tensor_mean - 3*tensor_dev
    
    tensor_max = torch.max(IR_tensor)
    tensor_min = torch.min(IR_tensor)
    return 2 * (IR_tensor - tensor_min) / (tensor_max - tensor_min) - 1


def screenANDscale_tensor2(IR_tensor, tensor_max):
    tensor_min = -1 * tensor_max
    return 2 * (IR_tensor - tensor_min) / (tensor_max - tensor_min) - 1


def prepare_input_IRs(Q_tensor):
    
    IR_A1 = []
    IR_A2 = []
    IR_B1 = []
    IR_B2 = []
    IR_X = []
    IR_Y = []
    step = 0
    
    Q_feature_list  = generate_Q_and_its_neighbors_feature(step,Q_tensor)
    IR_A1_one = []
    IR_A2_one = []
    IR_B1_one = []
    IR_B2_one = []
    IR_X_one = []
    IR_Y_one = []
    for i in range(0,len(Q_feature_list)):
        A1,A2,B1,B2,E = Changebasis(Q_feature_list[i],neighbor_type)
        IR_A1_one.append(A1)
        IR_A2_one.append(A2)
        IR_B1_one.append(B1)
        IR_B2_one.append(B2)
        temp_x = []
        temp_y =[]
        for j in range(0,len(E)):
            temp_x.append(E[j][0])
            temp_y.append(E[j][1])
        IR_X_one.append(temp_x)
        IR_Y_one.append(temp_y)
        
    
    IR_A1.append(IR_A1_one)
    IR_A2.append(IR_A2_one)
    IR_B1.append(IR_B1_one)
    IR_B2.append(IR_B2_one)
    IR_X.append(IR_X_one)
    IR_Y.append(IR_Y_one)
    
    IR_A1_tensor = torch.tensor(IR_A1)
    IR_A2_tensor = torch.tensor(IR_A2)
    IR_B1_tensor = torch.tensor(IR_B1)
    IR_B2_tensor = torch.tensor(IR_B2)
    IR_X_tensor = torch.tensor(IR_X)
    IR_Y_tensor = torch.tensor(IR_Y)
    
    
    scaled_A1 = screenANDscale_tensor2(IR_A1_tensor,A1_max).float().to(device)
    scaled_A2 = screenANDscale_tensor2(IR_A2_tensor,A2_max).float().to(device)
    scaled_B1 = screenANDscale_tensor2(IR_B1_tensor,B1_max).float().to(device)
    scaled_B2 = screenANDscale_tensor2(IR_B2_tensor,B2_max).float().to(device)
    scaled_X = screenANDscale_tensor2(IR_X_tensor,X_max).float().to(device)
    scaled_Y = screenANDscale_tensor2(IR_Y_tensor,Y_max).float().to(device)
    
    
    return scaled_A1, scaled_A2, scaled_B1, scaled_B2, scaled_X, scaled_Y
    
#############parameters############################################################################
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu") #is this correct?
print(device)
Lsize = 200
lattice_num = Lsize * Lsize
num_site = Lsize * Lsize
neighbor_ramp = 8
kT = 0.1
num_steps = 25000  # total steps of simulation?
par_steps = 50   # time step gap?

#Q_data = None
#velocity_data = None

Q_data = np.loadtxt("./ml_simulation/200/c4650.dat", usecols=(0))
velocity_data = np.loadtxt("./ml_simulation/200/c4650.dat", usecols=(3))

fp=open('para.csv') # this is the file generated by the training script
lines = fp.readlines()
for i in range(0,1):
    li=lines[i].split(",")
    A1_max=float(li[0])
    A2_max=float(li[1])
    B1_max=float(li[2])
    B2_max=float(li[3])
    X_max=float(li[4])
    Y_max=float(li[5])
fp.close()



#################################################################################################


neighbor_2d, num_input, neighbor_type = read_neighbor_list("./data_input/neighbor_" + str(Lsize) + "_ramp" + str(neighbor_ramp) + ".csv", neighbor_ramp, Lsize)

num_neighbor_layers = neighbor_type.shape[0]
num_of_nodes_neighbor_each_layer = []

for i in range(0,num_neighbor_layers):
    if (neighbor_type[i].item() == 0):
        num_of_nodes_neighbor_each_layer.append(1)
    elif (neighbor_type[i].item() == 1 or neighbor_type[i].item() == 2):
        num_of_nodes_neighbor_each_layer.append(4)
    elif (neighbor_type[i].item() == 3):
        num_of_nodes_neighbor_each_layer.append(8)
    else:
        print("I missed someting!")

##########################################################################################################



'''
torch.manual_seed(0)
ts = Lsize * Lsize
ls = Lsize
gamma = 0.2
dt = 0.05
kT = kT
kT_rand = 5.
k0 = 1.0
k1 = 0.18
G = 3.5
mass = 5.0
neighbor_2d = neighbor_2d

a_x = math.exp(-gamma * dt);
b_x = math.sqrt( (1. - pow(a_x, 2)) / mass );

Q = np.random.randn(ts) * math.sqrt(kT_rand / k1)



velocity = np.random.randn(ts) * math.sqrt(kT_rand / mass)

Q_tensor = torch.tensor(Q, dtype=torch.float64).view(1,-1).to(device)

print("This is Q_tensor: ", Q_tensor.shape)
#x_temp = Q_tensor[neighbor_2d]

scaled_A1, scaled_A2, scaled_B1, scaled_B2, scaled_X, scaled_Y = prepare_input_IRs(Q_tensor)

torch_data_set = data.TensorDataset(scaled_A1,scaled_A2,scaled_B1,scaled_B2,scaled_X,scaled_Y)
loader = data.DataLoader(dataset=torch_data_set, batch_size=1, shuffle=True)

for step, (scaled_A1,scaled_A2,scaled_B1,scaled_B2,scaled_X,scaled_Y) in enumerate(loader):
    print(scaled_A1.shape)

print(scaled_X.shape)
'''


